export const ReadinessCode = {
  POLICY_REQUIRED: "POLICY_REQUIRED",
  POLICY_EXPLICITLY_DISABLED_NON_PRODUCTION: "POLICY_EXPLICITLY_DISABLED_NON_PRODUCTION",
  POLICY_NOT_APPLICABLE: "POLICY_NOT_APPLICABLE",
  POLICY_UNRESOLVED: "POLICY_UNRESOLVED",
  POLICY_CONFLICT: "POLICY_CONFLICT",
  POLICY_DISABLE_NOT_AUTHORIZED: "POLICY_DISABLE_NOT_AUTHORIZED",
  POLICY_DISABLE_ON_PRODUCTION: "POLICY_DISABLE_ON_PRODUCTION",
  POLICY_ENVIRONMENT_UNRESOLVED: "POLICY_ENVIRONMENT_UNRESOLVED",
  EVIDENCE_MISSING: "EVIDENCE_MISSING",
  EVIDENCE_MALFORMED: "EVIDENCE_MALFORMED",
  DUPLICATE_KEY: "DUPLICATE_KEY",
  UNSUPPORTED_CONTRACT_VERSION: "UNSUPPORTED_CONTRACT_VERSION",
  INVALID_DECISION: "INVALID_DECISION",
  INVALID_TIMESTAMP: "INVALID_TIMESTAMP",
  READINESS_EXPIRED: "READINESS_EXPIRED",
  PROJECTION_BINDING_MISSING: "PROJECTION_BINDING_MISSING",
  PROJECTION_BINDING_MISMATCH: "PROJECTION_BINDING_MISMATCH",
  MAXIMUM_SIZE_EXCEEDED: "MAXIMUM_SIZE_EXCEEDED",
  MAXIMUM_DEPTH_EXCEEDED: "MAXIMUM_DEPTH_EXCEEDED",
  INTERNAL_EVALUATION_FAILURE_SANITIZED: "INTERNAL_EVALUATION_FAILURE_SANITIZED",
} as const;

export type ReadinessCode = (typeof ReadinessCode)[keyof typeof ReadinessCode];
