import { describe, it, expect } from "vitest";
import {
  READINESS_AUTHORITY_AGENT_CONFIG,
  READINESS_AUTHORITY_AGENT_DEFAULTS,
  READINESS_AUTHORITY_HIGHEST,
  READINESS_AUTHORITY_LOWEST,
  READINESS_AUTHORITY_ROUTE_CLASSIFICATION,
  READINESS_AUTHORITY_TEST_HARNESS,
} from "./types.js";

describe("Readiness types", () => {
  it("authority levels are ordered correctly", () => {
    expect(READINESS_AUTHORITY_HIGHEST).toBeLessThan(READINESS_AUTHORITY_AGENT_CONFIG);
    expect(READINESS_AUTHORITY_AGENT_CONFIG).toBeLessThan(READINESS_AUTHORITY_AGENT_DEFAULTS);
    expect(READINESS_AUTHORITY_AGENT_DEFAULTS).toBeLessThan(
      READINESS_AUTHORITY_ROUTE_CLASSIFICATION,
    );
    expect(READINESS_AUTHORITY_ROUTE_CLASSIFICATION).toBeLessThan(READINESS_AUTHORITY_TEST_HARNESS);
    expect(READINESS_AUTHORITY_TEST_HARNESS).toBeLessThan(READINESS_AUTHORITY_LOWEST);
  });
});
